steps:
  # Build Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--platform', 'linux/amd64',
      '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/finance-containers/auth-service:latest',
      '-f', 'src/auth-service/Dockerfile',
      '.'
    ]
    dir: '.'
    id: 'build-auth-service'

  # Push Auth Service to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'europe-west3-docker.pkg.dev/$PROJECT_ID/finance-containers/auth-service:latest'
    ]
    id: 'push-auth-service'
    waitFor: ['build-auth-service']

  # Deploy Auth Service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'auth-service',
      '--image', 'europe-west3-docker.pkg.dev/$PROJECT_ID/finance-containers/auth-service:latest',
      '--region', 'europe-west3',
      '--platform', 'managed',
      '--vpc-connector', 'athena-vpc-connector',
      '--vpc-egress', 'private-ranges-only',
      '--service-account', 'microservice-sa@$PROJECT_ID.iam.gserviceaccount.com',
      '--set-env-vars', 'PROJECT_ID=$PROJECT_ID,NODE_ENV=production,REGION=europe-west3',
      '--set-secrets', 'JWT_ACCESS_SECRET=jwt-access-secret:latest,JWT_REFRESH_SECRET=jwt-refresh-secret:latest',
      '--memory', '512Mi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--timeout', '300',
      '--concurrency', '100',
      '--allow-unauthenticated',
      '--port', '8080',
      '--execution-environment', 'gen2'
    ]
    id: 'deploy-auth-service'
    waitFor: ['push-auth-service']

  # Health check after deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [
      '-c',
      'SERVICE_URL=$$(gcloud run services describe auth-service --region=europe-west3 --format="value(status.url)") && echo "Testing auth service health at: $$SERVICE_URL/api/v1/auth/health" && for i in {1..10}; do echo "Health check attempt $$i/10..." && if curl -f -s "$$SERVICE_URL/api/v1/auth/health"; then echo "✅ Auth service health check passed"; exit 0; fi; sleep 10; done; echo "❌ Auth service health check failed after 10 attempts"; exit 1'
    ]
    id: 'auth-health-check'
    waitFor: ['deploy-auth-service']

substitutions:
  _SERVICE_HASH: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
  
timeout: '1200s'